In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
print(a.ndim) #checking the dimension

1


In [4]:
print(a.shape) #checking the numbers of rows and columns

(3,)


In [5]:
a = np.array([1, 2, 3], ndmin = 5) #making 5 dimension
print(a)

[[[[[1 2 3]]]]]


In [8]:
print(a.astype)

<built-in method astype of numpy.ndarray object at 0x00000244E13FEB10>


In [9]:
#Indexing in numpy
new_a = np.array([[1, 2, 3], [4, 5, 6]])
print(new_a[1][1])

5


In [10]:
print(new_a[0][-1])

3


In [11]:
#slicing
a = np.array([1, 2, 3, 4])
print(a[:2]) #where 2 means exclusion position

[1 2]


In [12]:
a = np.linspace(1, 3, 10)
print(a)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


In [13]:
a = np.array([1, 2, 3])
print(a.sum())

6


In [14]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[1, 2, 3], [4, 5, 6]])
print(x * y)

[[ 1  4  9]
 [16 25 36]]


In [15]:
print(x - y)

[[0 0 0]
 [0 0 0]]


In [17]:
print(np.vstack((x, y))) #vstack means vertical stack

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [18]:
print(np.hstack((x, y))) #hstack means horizontal stack

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [19]:
print(x.ravel())

[1 2 3 4 5 6]
